### PR TITLE
Added license

### PR DESCRIPTION
**Pull request by gdw2**

### CODE REVIEW

**Comment by cbas** [comment]
:-1: This is not a valid SPDX license identifier. It should be `Apache-2.0`.
See: http://spdx.org/licenses/Apache-2.0.html

**Comment by FredKSchott** [comment]
this PR should be closed (i don't have any permissions otherwise I would have myself).

**Comment by mikeal** [comment]
@FredKSchott made you an org owner :)

**Comment by FredKSchott** [comment]
👍

**Pull request closed without merging**
